### PR TITLE
[ENH]: HF Text Embedding Server docs

### PR DESCRIPTION
**Pull request by tazarov**
Ref:  chroma-core/chroma/pull/1371

### CODE REVIEW

**Comment by jeffchuber** [comment]
@tazarov can you add this to the sidebar as well? in `sidebars.js`

**Comment by tazarov** [comment]
@jeffchuber, done

**Comment by ZQ-Dev8** [comment]
Is this merged yet? I would really like to try chroma with a running TEI server. @jeffchuber

**Review by jeffchuber — APPROVED** [review]
approved with 1 nit

**Pull request merged**
