### PR TITLE
feat: CIP-2: Auth Providers

### PR DESCRIPTION
**Pull request by tazarov**
- Basic usage added to usage-guide.md

Refs: chroma-core/chroma#986

### CODE REVIEW

**Comment by tazarov** [comment]
@jeffchuber @HammadB I don't permissions to inspect what the problem might be.

**Comment by jeffchuber** [comment]
@tazarov we can fix this access... , but in the mean time

Screenshot 2023-08-22 at 11 25 37 AM

**Comment by tazarov** [comment]
thanks @jeffchuber I guess i missed the fact that I Can build/test locally. Let me try that.

**Comment by jeffchuber** [comment]
Cool :)

**Comment by tazarov** [comment]
@jeffchuber , figured it out. Looks good https://docs-git-fork-amikos-tech-feature-auth-chromacore.vercel.app/usage-guide

**Pull request merged**
