### PR TITLE
Add braintrust integration tutorial

### PR DESCRIPTION
**Pull request by davidatbraintrust**
Hi Chroma team,

Hope this is useful - I just included a link to the tutorial for evaluating a Chroma RAG app using Braintrust in the docs. 
https://www.braintrustdata.com/docs/examples/rag

Thank you,
David

### CODE REVIEW

**Comment by jeffchuber** [comment]
@davidatbraintrust nice! i am working on a docs refactor which will make our handling of integrations much cleaner (basically by enabling "subfolders"). 

I'm going to leave this open until that lands, ill tag you here.

**Comment by davidatbraintrust** [comment]
Awesome, thank you!

**Comment by jeffchuber** [comment]
@davidatbraintrust folders has dropped, do you mind adding a page to the integrations folder?

**Comment by davidatbraintrust** [comment]
Added page to integrations folder and updated the sidepanel for it. Thank you!

**Comment by jeffchuber** [comment]
@davidatbraintrust can we add a bit more info here? is there a ~30 lines of code example or tutorial that could go here? what value can an individual developer get from this?

**Comment by davidatbraintrust** [comment]
> @davidatbraintrust can we add a bit more info here? is there a ~30 lines of code example or tutorial that could go here? what value can an individual developer get from this?

Yes, added a quick code example and also there's a tutorial linked :) Thank you! Lmk if there's anything else I can add / improve.

**Comment by davidatbraintrust** [comment]
Lmk if there's anything else I can help with, thank you

**Pull request merged**
