### PR TITLE
first pass at Python API docs

### PR DESCRIPTION
**Pull request by jeffchuber**
### Improvements
- currently we have to manually regenerate the API docs and it is not hooked up as as part of `chroma` CI/CD
- formatting of `Examples` - a std python docstring is not great

Screenshot 2023-04-04 at 2 05 04 PM

- currently python only, I will add JS with the JS work i take on this week

### CODE REVIEW

**Comment by jeffchuber** [comment]
@levand @HammadB @atroyn what do you all think about this?

**Comment by jeffchuber** [comment]
@atroyn here's a direct link - https://docs-git-apidocs-chromacore.vercel.app/reference/local

**Comment by naynaly10** [comment]
> 



> ### Improvements
> * currently we have to manually regenerate the API docs and it is not hooked up as as part of `chroma` CI/CD
> * formatting of `Examples` - a std python docstring is not great
> 
> Screenshot 2023-04-04 at 2 05 04 PM
> 
> * currently python only, I will add JS with the JS work i take on this week

The formatting problem is likely caused by the tool used to convert the docstrings to markdown.
What tool did you use?

**Comment by jeffchuber** [comment]
@naynaly10 

Yes - I'd like examples to be well formatted as well. 

You can see the commands here:
https://github.com/chroma-core/docs/pull/28/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R37

**Comment by jeffchuber** [comment]
@HammadB @atroyn i would like your thoughts on the look and feel of this - see in the vercel deployed preview

**Comment by atroyn** [comment]
Put my initial comments on the preview via vercel directly

**Comment by jeffchuber** [comment]
Improving the python types so that the docs are fully accurate. WIP

**Review by HammadB — APPROVED** [review]

**Pull request merged**
