### PR TITLE
docs: add link to Jina documentation

### PR DESCRIPTION
**Pull request by JoanFM**
The Jina documentation is hard to discover

### CODE REVIEW

**Review by jeffchuber — APPROVED** [review]
thanks!

**Comment by jeffchuber** [comment]
@JoanFM should we add to sidebar as well?

**Comment by JoanFM** [comment]
> @JoanFM should we add to sidebar as well?

yes, where should I add this?

**Comment by jeffchuber** [comment]
@JoanFM https://github.com/chroma-core/docs/blob/c676a53a218fda1a4cb3cc239601b31f1862169f/sidebars.js#L91

**Comment by JoanFM** [comment]
> @JoanFM
> 
> https://github.com/chroma-core/docs/blob/c676a53a218fda1a4cb3cc239601b31f1862169f/sidebars.js#L91

perf, will raise a PR soon

**Comment by JoanFM** [comment]
#189 should do it

**Pull request merged**
