### PR TITLE
fix: replace Client by EphemeralClient

### PR DESCRIPTION
**Pull request by candidosales**

### CODE REVIEW

**Comment by jeffchuber** [comment]
@HammadB tagging you for review since you had landed the other docs update

**Comment by HammadB** [comment]
Client is still technically supported and by default is Ephemeral. So this is mostly a question of which we want to make more standard. @candidosales could you give some context on this change?

**Comment by candidosales** [comment]
@HammadB, Thank you for clarifying. After reading about the migration to Chroma 0.4.0, I had the impression that the Client would be replaced by the EphemeralClient.

**Comment by HammadB** [comment]
Closing this out as we decided to stick with Client()

**Pull request closed without merging**
