### PR TITLE
[DOC] [ENH] Add a local search bar to the documentation

### PR DESCRIPTION
**Pull request by devanshkaloti**
- Allow visitors to search through the documentation
- Added https://github.com/cmfcmf/docusaurus-search-local (local client side search) 
- Customized the CSS to match the existing theme

**Search Bar (Top Right)**
Screenshot 2024-03-09 at 12 28 24 PM

**Search Results**
Screenshot 2024-03-09 at 12 28 36 PM

**Result**
Screenshot 2024-03-09 at 12 28 46 PM

### CODE REVIEW

**Comment by jeffchuber** [comment]
@devanshkaloti thanks! 

im actively working a large refactor of the docs - moving away from docusaurus. 

Im currently leaning towards wiring up `flexsearch` - any experience there?

**Comment by devanshkaloti** [comment]
Hi @jeffchuber, unfortunately I don't have experience with `flexsearch`. I can take a look at it if you would like.

Would you still consider to add this local search bar PR in interim or is the new docs platform coming up quickly?

Thanks!

**Comment by jeffchuber** [comment]
@devanshkaloti this is really! how is the data fed in? does it connect to algolia? does docusuarus magically build the index at build time?

i think we can def get this merged :)

**Comment by devanshkaloti** [comment]
Hey @jeffchuber, that's great to hear! 

I'm using https://github.com/cmfcmf/docusaurus-search-local which is one of the options listed in the "[using local search](https://docusaurus.io/docs/search#using-your-own-search)" option. 

It does not connect to algolia for anything at all. Everything is done local (index creation, search etc). Only algolia/autocomplete is used to provide the React component (see note below). Now, on a deeper look, I do see `@algolia/client-analytics@4.22.1` listed as a dependancy which I'm not a fan of nor do I see the need for this. 

The https://github.com/cmfcmf/docusaurus-search-local repo says: 
> Note: We use the open source [algolia/autocomplete](https://github.com/algolia/autocomplete) library for the searchbox. This library is just used as the frontend, and, unlike the default Docusaurus search experience ([algolia/docsearch](https://docsearch.algolia.com/)), does not connect to any Algolia or third-party servers.

It seems like it's using [lunr.js](https://github.com/olivernn/lunr.js) which creates an index file at build time (all local) `search-index-docs-default-current.json`, and then this file is loaded for the search.

**Comment by jeffchuber** [comment]
@devanshkaloti super cool! 

one meta critique of docusaurus is that it has a bit too much magic. 

do you know if the index is customizable at all? for example I would expect this to return something 

Screenshot 2024-03-13 at 9 16 37 PM

**Comment by devanshkaloti** [comment]
@jeffchuber, I agree with you. 

We have some customization options:
```
 // lunr.js-specific settings
  lunr: {
    // When indexing your documents, their content is split into "tokens".
    // Text entered into the search box is also tokenized.
    // This setting configures the separator used to determine where to split the text into tokens.
    // By default, it splits the text at whitespace and dashes.
    //
    // Note: Does not work for "ja" and "th" languages, since these use a different tokenizer.
    tokenizerSeparator: /[\s\-]+/,
    // https://lunrjs.com/guides/customising.html#similarity-tuning
    //
    // This parameter controls the importance given to the length of a document and its fields. This
    // value must be between 0 and 1, and by default it has a value of 0.75. Reducing this value
    // reduces the effect of different length documents on a term’s importance to that document.
    b: 0.75,
    // This controls how quickly the boost given by a common word reaches saturation. Increasing it
    // will slow down the rate of saturation and lower values result in quicker saturation. The
    // default value is 1.2. If the collection of documents being indexed have high occurrences
    // of words that are not covered by a stop word filter, these words can quickly dominate any
    // similarity calculation. In these cases, this value can be reduced to get more balanced results.
    k1: 1.2,
    // By default, we rank pages where the search term appears in the title higher than pages where
    // the search term appears in just the text. This is done by "boosting" title matches with a
    // higher value than content matches. The concrete boosting behavior can be controlled by changing
    // the following settings.
    titleBoost: 5,
    contentBoost: 1,
    tagsBoost: 3,
    parentCategoriesBoost: 2, // Only used when indexDocSidebarParentCategories > 0
  }
```

I could not find exactly how to customize the index ourselves. Technically we should be able to process and edit the local file generated at build time, I can take a look at this further but it will most likely require further effort.

**Comment by jeffchuber** [comment]
@devanshkaloti no worries! i think at this point it's not worth the lift. I should land the docs refactor by Monday - my plan to use algolia which I think will auto-build and maintain the index. It appears to do well searches like `.query`

**Pull request closed without merging**
