### PR TITLE
client sdk observability docs

### PR DESCRIPTION
**Pull request by nirga**
Added docs on how to instrument Chroma SDK calls for tracing RAG pipelines e2e using [OpenLLMetry](https://www.openllmetry.com) - an open source set of extensions built on top of OpenTelemetry that instruments foundation models, vector DBs and LLM frameworks.

### CODE REVIEW

**Comment by jeffchuber** [comment]
@nirga this could be an https://docs.trychroma.com/integrations - but shouldnt go here.

**Comment by nirga** [comment]
@jeffchuber 🤔 
The reason I put it here is because this was the natural place people would search for "how do I get observability for my Chroma requests". This is actually where I came looking for observability for Chroma 😅 . 
I tried using it but then realized it's only for the DB itself, not for the client. So I tend to think the integration page is less of a natural place to put such things (which indeed contains framework integrations and not observability solutions). This is kind of in line to how we were added to [LlamaIndex](https://gpt-index.readthedocs.io/en/stable/module_guides/observability/observability.html#openllmetry).

**Comment by jeffchuber** [comment]
I'd be fine linking to the integration page at the bottom of the
observability page.... thoughts?

**Comment by nirga** [comment]
Done ✅  @jeffchuber 
LMK if this is how you meant. I still kept the change in the observability docs, which clearly stated that the section there is more for backend / db observability as I personally was confused by it but let me know if you'd like me to revert it entirely and just leave a link at the bottom.

**Comment by nirga** [comment]
Hey @jeffchuber WDYT? Is that ok to merge?

**Review by beggers — APPROVED** [review]
Looks good!

**Pull request merged**
