### PR TITLE
Update embeddings.md

### PR DESCRIPTION
**Pull request by l4b4r4b4b4**
Be more concise on how to pass  Azure deployment name to OpenAI Embeddings.

### CODE REVIEW

**Comment by jeffchuber** [comment]
@l4b4r4b4b4 I may have missed it, but does OpenAI support fine-tuning embedding models? at least that's what comes to mind when i see `YOUR_EMBEDDINGS_DEPLOYMENT_NAME`

**Comment by l4b4r4b4b4** [comment]
nope it doesn't. Passing `YOUR_EMBEDDINGS_DEPLOYMENT_NAME` is specific when using azure and it was missing in the documentation, that you have to set it under `model_name` parameter.

**Comment by jeffchuber** [comment]
@l4b4r4b4b4 is this an accurate rephrasing? 

Before:`In this case you have to pass the deployment name of your deployed OpenAI embeddings model as `model_name` parameter:`

After: `(For Azure hosted models, be sure to configure 'model_name' as well)`

**Comment by jeffchuber** [comment]
closing because this is stale - let me know if you would like to re-open!

**Pull request closed without merging**
