### PR TITLE
Add docs to reflect duplicate ID validation

### PR DESCRIPTION
**Pull request by levand**
This should NOT be merged until the corresponding functionality in `lukev/validate_add` branch in `chromadb` gets merged to main.

### CODE REVIEW

**Comment by jeffchuber** [comment]
@levand i think this can be merged now?

**Comment by jeffchuber** [comment]
@HammadB do you know if this can be merged?

**Comment by HammadB** [comment]
We can merge it for now. However the sqllite refactor will change this behavior to silently fail.

**Comment by jeffchuber** [comment]
@HammadB merged, can you link me to the discussion about silently failing? Seems like users will likely be making a mistake using duplicate ids and we should let them know vs silently fail.

**Pull request merged**
